### PR TITLE
Create Top10.ipynb

### PR DESCRIPTION
**Pull request by abhisennin**
This is the Top 10 calls on 311

### CODE REVIEW

**Comment by hekaikyle** [comment]
i think since the file called 311_Service_Requests_2020.csv is in the *same directory* as the notebook file, we don't need to include the path in the pd.read_csv() function.
just pd.read_csv("311_Service_Requests_2020.csv") would be fine.
otherwise when the grader runs the code, it will be an error.

**Comment by Abhi-sennin** [comment]
> i think since the file called 311_Service_Requests_2020.csv is in the _same directory_ as the notebook file, we don't need to include the path in the pd.read_csv() function. just pd.read_csv("311_Service_Requests_2020.csv") would be fine. otherwise when the grader runs the code, it will be an error.

Hi, I tried that earlier but it did not work

**Comment by hekaikyle** [comment]
did you put the csv file in the same folder as the ipynb file?

**Comment by Abhi-sennin** [comment]
> did you put the csv file in the same folder as the ipynb file?

Of course

**Pull request merged**
